ref  <-FLlst()
srr  <-FLlst()

      srr[["cushing"]]  <-as.FLSR(her4[["ices"]])
model(srr[["cushing"]]) <-cushing()
      srr[["cushing"]]  <-fmle(srr[["cushing"]] )
      ref[["cushing"]]  <-brp(FLBRP(her4[["ices"]],fbar=seq(0,1,length.out=101),sr=srr[["cushing"]] ))
predict(srr[["cushing"]],ssb=ssb(ref[["cushing"]]))==rec(ref[["cushing"]])
plot( ref[["cushing"]])

      srr[["geomean"]]  <-as.FLSR(her4[["ices"]])
model(srr[["geomean"]]) <-geomean()
      srr[["geomean"]]  <-fmle(srr[["geomean"]] )
      ref[["geomean"]]  <-brp(FLBRP(her4[["ices"]],fbar=seq(0,1,length.out=101),sr=srr[["geomean"]] ))
predict(srr[["geomean"]],ssb=ssb(ref[["geomean"]]))==rec(ref[["geomean"]])
plot( ref[["geomean"]])

      srr[["bevholt"]]  <-as.FLSR(her4[["ices"]])
model(srr[["bevholt"]]) <-bevholt()
      srr[["bevholt"]]  <-fmle(srr[["bevholt"]] )
      ref[["bevholt"]]  <-brp(FLBRP(her4[["ices"]],fbar=seq(0,1,length.out=101),sr=srr[["bevholt"]] ))
predict(srr[["bevholt"]],ssb=ssb(ref[["bevholt"]]))==rec(ref[["bevholt"]])
plot( ref[["bevholt"]])

      srr[["ricker"]]  <-as.FLSR(her4[["ices"]])
model(srr[["ricker"]]) <-ricker()
      srr[["ricker"]]  <-fmle(srr[["ricker"]] )
      ref[["ricker"]]  <-brp(FLBRP(her4[["ices"]],fbar=seq(0,1,length.out=101),sr=srr[["ricker"]] ))
predict(srr[["ricker"]],ssb=ssb(ref[["ricker"]]))==rec(ref[["ricker"]])
plot( ref[["ricker"]])

      srr[["shepherd"]]  <-as.FLSR(her4[["ices"]])
model(srr[["shepherd"]]) <-shepherd()
      srr[["shepherd"]]  <-fmle(srr[["shepherd"]] )
      ref[["shepherd"]]  <-brp(FLBRP(her4[["ices"]],fbar=seq(0,1,length.out=101),sr=srr[["shepherd"]] ))
predict(srr[["shepherd"]],ssb=ssb(ref[["shepherd"]]))==rec(ref[["shepherd"]])
plot( ref[["shepherd"]])

      srr[["segreg"]]  <-as.FLSR(her4[["ices"]])
model(srr[["segreg"]]) <-segreg()
      srr[["segreg"]]  <-fmle(srr[["segreg"]] )
params(srr[["segreg"]])<-params(srr[["segreg"]])[c("a","b"),]
      ref[["segreg"]]  <-brp(FLBRP(her4[["ices"]],fbar=seq(0,1,length.out=101),sr=srr[["segreg"]] ))
predict(srr[["segreg"]],ssb=ssb(ref[["segreg"]]))==rec(ref[["segreg"]])
plot( ref[["segreg"]])
