                                                                                                                                    
!                                                                                                                                   
!     This data block holds the data labels                                                                                         
!                                                                                                                                   
!                                                                                                                                   
!                                                                                                                                   
!                                                                                                                                   
                                                                                                                                    
      Character*40 MainTitle                                                                                                        
      Character*40 ASurvLab(MaxSurvey)                                                                                              
      Character*40 BSurvLab(MaxBsurv)                                                                                               
                                                                                                                                    
                                                                                                                                    
      COMMON /LABELS / MainTitle, ASurvLab, BSurvLab                                                                                
