    ftn90 /ca  /debug    ica2_90 /ca  /debug  
   ftn90 /ca  /debug     ica
    ftn90 /ca  /debug     pctile
   ftn90 /ca  /debug      in 
    ftn90 /ca  /debug      out 
   ftn90 /ca  /debug     wtab 
     ftn90 /ca  /debug    stats 
    ftn90 /ca  /debug    parmset 
   ftn90 /ca  /debug    io_win 
     ftn90 /ca  /debug    io_dos 
     ftn90 /ca  /debug    sepvpa
     ftn90 /ca  /debug     convpa
     ftn90 /ca  /debug   cvpa1
 ftn90 /ca  /debug     wblk
 ftn90 /ca  /debug    object
     ftn90 /ca  /debug     srr
     ftn90 /ca  /debug    shrink
echo     ftn90 /ca  /debug nmac3
     ftn90 /ca  /debug by
slink li
 







