   ftn90       ica2_90     
  ftn90        ica
   ftn90        pctile
  ftn90         in 
   ftn90         out 
  ftn90        wtab 
    ftn90       stats 
   ftn90       parmset 
  ftn90       io_win 
    ftn90       io_dos 
    ftn90       sepvpa
    ftn90        convpa
    ftn90      cvpa1
   ftn90        wblk
ftn90       object
    ftn90        srr
    ftn90       shrink
    ftn90    nmac3
    ftn90    by
echo slink li
 







