                                                                                                                                    
      H(1,1) ='Enter the name of the index file'                                                                                    
      H(1,2) ='Teclee el nombre del archivo indice'                                                                                 
      H(1,3) ='Frapper le nom du fichier index'                                                                                     
      H(1,4) ='Skriv navnet av indeksarkiv'                                                                                         
                                                                                                                                    
      H(2,1)= 'No index file name. Run abandonded'                                                                                  
      H(2,2)= 'No se encontr¢ el archivo indice.'                                                                                   
      H(2,3)= 'Le fichier index n''a pas ‚t‚ trouv‚.'                                                                               
      H(2,4)= 'Indeksarkiv var ikke funnet.'                                                                                        
                                                                                                                                    
      H(3,1)= 'File not found. Try again ?'                                                                                         
      H(3,2)= 'No se encontr¢ el archivo. ? Otro intento ?'                                                                         
      H(3,3)= 'Le fichier n''a pas ‚t‚ trouv‚. Un autre essai ?'                                                                    
      H(3,4)= 'Arkivet var ikke funnet. Et forsoek til ?'                                                                           
                                                                                                                                    
      H(4,1)= 'Landings file format error.'                                                                                         
      H(4,2)= 'Error en el formato del archivo de desembarques.'                                                                    
      H(4,3)= 'Le format du fichier des captures n''est pas correcte.'                                                              
      H(4,4)= 'Formatet av fangstarkivet er urett.'                                                                                 
                                                                                                                                    
      H(5,1)='Too many years in the data. The Maximum is '                                                                          
      H(5,2)='Demasiado a¤os en los datos. El M ximo es'                                                                            
      H(5,3)='Trop d''ann‚es dans les donn‚es. Le maximum est'                                                                      
      H(5,4)='Overm†l †r i data. Maksimum er '                                                                                      
                                                                                                                                    
      H(6,1)='Too many ages in the data. The Maximum is '                                                                           
      H(6,2)='Demasiado edades en los datos. El M ximo es '                                                                         
      H(6,3)='Trop d''ages dans les donn‚es. Le maximum est'                                                                        
      H(6,4)='Overm†l alderer i fangstdata. Maksimum er '                                                                           
                                                                                                                                    
      H(7,1)='The catch numbers file identifier is wrong.'                                                                          
      H(7,2)='La identificaci¢n del archivo de capturas en numero es'// &                                                           
     * ' err¢nea.'                                                                                                                  
      H(7,3)='L''identification du fichier de numeros de captures'//    &                                                           
     * 'est incorrecte.'                                                                                                            
      H(7,4)='Arkiv av fangst i nummer er galt identifisert.'                                                                       
                                                                                                                                    
      H(8,1)='Error in year range of catch numbers file.'                                                                           
      H(8,2)='El rango de a¤os en el archivo de capturas en '           &                                                           
     * //'n£mero es err¢neo.'                                                                                                       
      H(8,3)='Le choix d''ann‚es dans le fichier de numeros de'         &                                                           
     * //'captures est incorrecte.'                                                                                                 
      H(8,4)='Valget av †r i arkiv av fangst i nummer er galt.'                                                                     
                                                                                                                                    
      H(9,1)='Error in age range of catch numbers file.'                                                                            
      H(9,2)='El rango de edades en el archivo de capturas en '         &                                                           
     * //'n£mero es err¢neo.'                                                                                                       
      H(9,3)='Le choix d''ages dans le fichier de numeros de'           &                                                           
     * //'captures est incorrecte.'                                                                                                 
      H(9,4)='Valget av alderer i arkivet av fangst i nummer er galt.'                                                              
                                                                                                                                    
      H(10,1)='Catch numbers file must be matrix format.'                                                                           
      H(10,2)='El archivo de capturas en n£mero ha de estar en'         &                                                           
     *//' formato de matriz.'                                                                                                       
      H(10,3)='Le fichier de numeros de captures doit ˆtre format‚'     &                                                           
     *//' en matrice.'                                                                                                              
      H(10,4)='Arkivet av fangst i nummer m† ha matrise format.'                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
      HK(1,1)='No of years for separable constraint ?'                                                                              
      HK(1,2)='No de a¤os para aplicar el modelo separable ?'                                                                       
      HK(1,3)='No d''ann‚es pour utiliser le modŠle separable ?'                                                                    
      HK(1,4)='Hvor mange †r m† brukes i atskillelig modellen ?'                                                                    
                                                                                                                                    
      HK(2,1)='Reference age for separable constraint ?'                                                                            
      HK(2,2)='Edad de referencia para el modelo separable ?'                                                                       
      HK(2,3)='Age de reference pour le modŠle separable ?'                                                                         
      HK(2,4)='Hensvisningsalder for atskillelig modellen ?'                                                                        
                                                                                                                                    
      HK(3,1)='Constant selection pattern model (Y/N) ?'                                                                            
      HK(3,2)='Modelo de selecci¢n constante (S/N) ?'                                                                               
      HK(3,3)='ModŠle de selection constante (O/N) ?'                                                                               
      HK(3,4)='Konstantvelging modellen (J/N) ?'                                                                                    
                                                                                                                                    
      KO(1,1)='yYnN'                                                                                                                
      KO(1,2)='sSnN'                                                                                                                
      KO(1,3)='oOnN'                                                                                                                
      KO(1,4)='jJnN'                                                                                                                
                                                                                                                                    
      Ky(1,1) = 'yY'                                                                                                                
      Ky(1,2) = 'sS'                                                                                                                
      Ky(1,3) = 'oO'                                                                                                                
      Ky(1,4) = 'jJ'                                                                                                                
                                                                                                                                    
      HK(4,1)='Enter last year in which selection is constant '                                                                     
      HK(4,2)='Teclee el £ltimo a¤o en que el patr¢n de selecci¢n es'   &                                                           
     *//' constante'                                                                                                                
      HK(4,3)='Frapper la derniŠre ann‚e o£ la selection est constante'                                                             
      HK(4,4)='Siste †r for konstant velging '                                                                                      
                                                                                                                                    
      HK(5,1) = 'Gradual or Abrupt chage in selection (G/A) ? '                                                                     
      HK(5,2) = 'Cambio en selecci¢n Brusco o Lento (B/L) ? '                                                                       
      HK(5,3) = 'Changement de selection Abrupte ou Lent (A/L) ? '                                                                  
      HK(5,4) = 'Forandringen i velging er Plutselig eller Gradvis'     &                                                           
     *//' (P/G) ?'                                                                                                                  
                                                                                                                                    
      KO(2,1) = 'gGaA'                                                                                                              
      KO(2,2) = 'bBlL'                                                                                                              
      KO(2,3) = 'aAlL'                                                                                                              
      KO(2,4) = 'pPgG'                                                                                                              
                                                                                                                                    
      KY(2,1) = 'aA'                                                                                                                
      KY(2,2) = 'Bb'                                                                                                                
      KY(2,3) = 'aA'                                                                                                                
      KY(2,4) = 'pP'                                                                                                                
                                                                                                                                    
      HK(6,1)='S to be fixed on last age ?'                                                                                         
      HK(6,2)='Valor de selecci¢n fijado a la £ltima edad ? '                                                                       
      HK(6,3)='Valeur de selection a fixer pour le dernier age ?'                                                                   
      HK(6,4)='Velgingsverdien for den siste aldren ?'                                                                              
                                                                                                                                    
      HK(7,1)='S for last age in later selection pattern ?'                                                                         
      HK(7,2)='Valor de selecci¢n terminal para el segundo patr¢n'      &                                                           
     * // ' de selecci¢n ?'                                                                                                         
      HK(7,3)='Valeur de selection terminale pour la deuxiŠme periode'                                                              
      HK(7,4)='Velgingsverdien for den siste aldren i den andre'        &                                                           
     *//' perioden'                                                                                                                 
                                                                                                                                    
      HK(8,1)='First age for calculation of reference F ?'                                                                          
      HK(8,2)='Primera edad para el c lculo de la F de referencia ?'                                                                
      HK(8,3)='PremiŠre age pour le calcul de la F de reference ?'                                                                  
      HK(8,4)='Foerste alder for beregningen av hensvisning '           &                                                           
     *//' F-verdien ?'                                                                                                              
                                                                                                                                    
      HK(9,1)='Last age for calculation of reference F ?'                                                                           
      HK(9,2)='Ultima edad para el c lculo de la F de referencia ?'                                                                 
      HK(9,3)='DerniŠre age pour le calcul de la F de reference ?'                                                                  
      HK(9,4)='Siste alder for beregningen av hensvisning '             &                                                           
     *//' F-verdien ?'                                                                                                              
                                                                                                                                    
      HK(10,1)='First is older than last ! Try again. '                                                                             
      HK(10,2)='La primera es mayor que la £ltima. Intente otra vez.'                                                               
      HK(10,3)='La premiŠre est plus ag‚e que la derniŠre.'             &                                                           
     *//' Essayez de nouveau.'                                                                                                      
      HK(10,4)='Den siste alder er mindre gamle at den foerste.'        &                                                           
     *//' Forsoek til.'                                                                                                             
                                                                                                                                    
      HK(11,1) ='Use default weighting ?'                                                                                           
      HK(11,2) ='Usar la ponderaci¢n est ndar ?'                                                                                    
      HK(11,3) ='Utiliser les valeurs de lambda recommend‚es ?'                                                                     
      HK(11,4) ='Bruker normalbetingelse for lambda-verdier ?'                                                                      
                                                                                                                                    
      HK(12,1)='Enter relative weights at age '                                                                                     
      HK(12,2)='Teclee la ponderaci¢n deseada por cada edad '                                                                       
      HK(12,3)='Frapper la valeur de lambda desir‚e pour chaque age '                                                               
      HK(12,4)='Skriv behoevde verdiene for lambda i hver alder'                                                                    
                                                                                                                                    
      HK(13,1)='Weight for age'                                                                                                     
      HK(13,2)='Ponderaci¢n a la edad '                                                                                             
      HK(13,3)='Lambda pour l''age '                                                                                                
      HK(13,4)='Nye verdien for lambda for alderen '                                                                                
                                                                                                                                    
      HK(14,1)='Enter relative weights by year '                                                                                    
      HK(14,2)='Teclee ponderaci¢n deseada por a¤o  '                                                                               
      HK(14,3)='Frapper les valeur de lambda pour chaque ann‚e '                                                                    
      HK(14,4)='Skriv behoevde verdiene for lambda i hver †r'                                                                       
                                                                                                                                    
      HK(15,1)='Weight for year'                                                                                                    
      HK(15,2)='Ponderaci¢n para el a¤o'                                                                                            
      HK(15,3)='Lambda pour l''ann‚e'                                                                                               
      HK(15,4)='Nye verdien for lambda for †ret'                                                                                    
                                                                                                                                    
      HK(16,1)='Enter new weights for specified years and ages'         &                                                           
     *//' if needed'                                                                                                                
      HK(16,2)='Teclee nueva ponderaci¢n para determinados a¤os'        &                                                           
     *//'o edades'                                                                                                                  
      HK(16,3)='Frapper des nouvelles valeurs de lambda pour'           &                                                           
     *//' certaines ages ou ann‚es'                                                                                                 
      HK(16,4)='Skriv nye verdier av lambda for hver †r og alder'                                                                   
                                                                                                                                    
      HK(17,1)='Enter year, age, new weight or -1,-1,-1 to end.'                                                                    
      HK(17,2)='Teclee a¤o, edad, nueva ponderaci¢n o -1,-1,-1 '        &                                                           
     *//'para acabar'                                                                                                               
      HK(17,3)='Frapper l''an, l''age, lambda ou -1,-1,-1 pour finir.'                                                              
      HK(17,4)='Skriv †r, alder, lamba eller -1,-1,-1 til ende.'                                                                    
                                                                                                                                    
      HK(18,1)='Is the last age of '                                                                                                
      HK(18,2)='Es la £ltima edad de '                                                                                              
      HK(18,3)='Est-ce-que la derniŠre age de '                                                                                     
      HK(18,4)='Er den siste †ret av '                                                                                              
                                                                                                                                    
      HK(19,1)='a plus-group (Y/y) ? '                                                                                              
      HK(19,2)='una clase acumulada ? '                                                                                             
      HK(19,3)='est une classe accumul‚e (O/N) ?'                                                                                   
      HK(19,4)='en kumulativ klasse (J/N) ?'                                                                                        
                                                                                                                                    
      HK(20,1)='You must choose a catchability model for each index.'                                                               
      HK(20,2)='Vd. debe elegir un modelo de capturabilidad por cada'   &                                                           
     *//' indice.'                                                                                                                  
      HK(20,3)='Vous devez choisir un modŠle de capturabilit‚ pour '    &                                                           
     *//' chaque indice d''abondance.'                                                                                              
      HK(20,4)='De m† velge en fangstmodell for hver indeks av'         &                                                           
     *//' mengde.'                                                                                                                  
                                                                                                                                    
      HK(21,1)='Models:   A  Absolute:  Index = Abundance . e'                                                                      
      HK(21,2)='Modelos:  A  Absoluto:  Indice = Abundancia . e'                                                                    
      HK(21,3)='ModŠles:  A  Absolut:   Indice = Abondance . e'                                                                     
      HK(21,4)='Modeller: A  Absolutt:  Indeks = Mengde . e'                                                                        
                                                                                                                                    
      HK(22,1)='          L  Linear:    Index = Q. Abundance . e '                                                                  
      HK(22,2)='          L  Lineal:    Indice = Q. Abundancia . e'                                                                 
      HK(22,3)='          L  Lineaire:  Indice = Q. Abondance . e'                                                                  
      HK(22,4)='          L  Line‘r:    Indice = Q. Mengde . e'                                                                     
                                                                                                                                    
      HK(23,1)='          P  Power:     Index = Q. Abundance^ K .e'                                                                 
      HK(23,2)='          P  exPonente: Indice = Q. Abundancia^ K .e'                                                               
      HK(23,3)='          P  exPonent:  Indice = Q. Abondance^K . e'                                                                
      HK(23,4)='          P  eksPonent: Indeks = Q. Mengde^K . e'                                                                   
                                                                                                                                    
      HK(24,1)='   where Q and K are parameters to be estimated, and'                                                               
      HK(24,2)='   d¢nde Q y K son par metros a estimar, y'                                                                         
      HK(24,3)='   ou Q et K sont des paramŠtres a estimer, et'                                                                     
      HK(24,4)='   som Q og K er parameter † beregne, og'                                                                           
                                                                                                                                    
      HK(25,1)='   e is a lognormally-distributed error.'                                                                           
      HK(25,2)='   e es error con distribuci¢n lognormal.'                                                                          
      HK(25,3)='   e est une erreur avec distribution log-normale.'                                                                 
      HK(25,4)='   e er error med lognormal distribusjon.'                                                                          
                                                                                                                                    
                                                                                                                                    
      HK(26,1)='Model for '                                                                                                         
      HK(26,2)='Modelo para '                                                                                                       
      HK(26,3)='Le modŠle pour '                                                                                                    
      HK(26,4)='Modell for '                                                                                                        
                                                                                                                                    
      HK(27,1)=' is to be A/L/P ?'                                                                                                  
      HK(27,2)=' a ser A/L/P ?'                                                                                                     
      HK(27,3)=' doit ˆtre A/L/P ?'                                                                                                 
      HK(27,4)=' m† v‘re A/L/P ?'                                                                                                   
                                                                                                                                    
      HK(28,1)='There are '                                                                                                         
      HK(28,2)='Faltan '                                                                                                            
      HK(28,3)='Il manque '                                                                                                         
      HK(28,4)='Er '                                                                                                                
                                                                                                                                    
      HK(29,1)=' missing observations for fitting the separable'        &                                                           
     *//' model.'                                                                                                                   
      HK(29,2)=' observaciones para el ajuste del modelo separable.'                                                                
      HK(29,3)=' observations pour ajuster le modŠle separable.'                                                                    
      HK(29,4)=' frav‘rende data † tilpasse konstantvelging modellen.'                                                              
                                                                                                                                    
      HK(30,1)='MODEL OVERPARAMETERISED'                                                                                            
      HK(30,2)='INSUFFICIENTE DATOS PARA EL MODELO ELEGIDO'                                                                         
      HK(30,3)='TROP DE PARAMETRES POUR LES DONNEES DISPONIBLES'                                                                    
      HK(30,4)='IKKE NOK DATA FOR MODELLEN'                                                                                         
                                                                                                                                    
      HK(31,1)='Too few data in fitting the index : '                                                                               
      HK(31,2)='En el ajuste del ¡ndice : '                                                                                         
      HK(31,3)='Dans l''indice d''abondance : '                                                                                     
      HK(31,4)='I mengde-indeks : '                                                                                                 
                                                                                                                                    
      HK(42,1)=' at age '                                                                                                           
      HK(42,2)=' a la edad '                                                                                                        
      HK(42,3)=' a l''age '                                                                                                         
      HK(42,4)=' p† alder '                                                                                                         
                                                                                                                                    
                                                                                                                                    
      HK(32,1)='Fit a stock-recruit relationship (Y/N) ?'                                                                           
      HK(32,2)='Inclu¡r una relaci¢n stock-recluta (S/N) ?'                                                                         
      HK(32,3)='Ajouter une relation stock-recrues (O/N) ?'                                                                         
      HK(32,4)='Tilpass en bestand-rekrutt funksjon (J/N) ?'                                                                        
                                                                                                                                    
      HK(33,1)='Enter the time lag in years between spawning'           &                                                           
     *//' and the stock size'                                                                                                       
      HK(33,2)='Teclee el lapso de tiempo en a¤os entre el'             &                                                           
     *//' desove y reclutamiento'                                                                                                   
      HK(33,3)='Frapper la periode de temps entre la ponte et le'       &                                                           
     *//' recrutement'                                                                                                              
      HK(33,4)='Tidsavnittet mellom gyten og rekrutter'                                                                             
                                                                                                                                    
      HK(34,1)=' of fish aged '                                                                                                     
      HK(34,2)=' a la edad '                                                                                                        
      HK(34,3)=' a l''age '                                                                                                         
      HK(34,4)=' som er '                                                                                                           
                                                                                                                                    
      HK(35,1)=' years on 1 January. '                                                                                              
      HK(35,2)=' a¤os el d¡a 1 enero. '                                                                                             
      HK(35,3)=' ans le 1 Janvier.'                                                                                                 
      HK(35,4)=' †r gammel p† 1 januar.'                                                                                            
                                                                                                                                    
      HK(36,1)='This will probably be '                                                                                             
      HK(36,2)='Esto podr¡a ser '                                                                                                   
      HK(36,3)='Ce‡i pourrait ˆtre '                                                                                                
      HK(36,4)='De kan v‘re '                                                                                                       
                                                                                                                                    
      HK(37,1)='unless the stock is an autumn-spawning herring'                                                                     
      HK(37,2)='salvo si el recurso es un arenque que desova en oto¤o'                                                              
      HK(37,3)='sauf s''il s''agit d''un hareng qui pond en automne.'                                                               
      HK(37,4)='unntatt som er hoestgytende sild'                                                                                   
                                                                                                                                    
      HK(38,1)=' in which case it will probably be '                                                                                
      HK(38,2)=' en cual caso probablemente ser  '                                                                                  
      HK(38,3)=' Dans ce cas ce sera probablement '                                                                                 
      HK(38,4)=' I s† fall det can v‘re '                                                                                           
                                                                                                                                    
      HK(43,1) = ' years.'                                                                                                          
      HK(43,2) = ' a¤os.'                                                                                                           
      HK(43,3) = ' ann‚es.'                                                                                                         
      HK(43,4) = ' †r. '                                                                                                            
                                                                                                                                    
                                                                                                                                    
      HK(39,1)='Enter the lag in years (rounded up) '                                                                               
      HK(39,2)='Teclee el lapso en a¤os completos '                                                                                 
      HK(39,3)='Frapper la periode en ann‚es entiŠres '                                                                             
      HK(39,4)='Skriv tidsavnittet i hele †rene '                                                                                   
                                                                                                                                    
      HK(40,1)='File not found: '                                                                                                   
      HK(40,2)='No se encontr¢ el archivo: '                                                                                        
      HK(40,3)='Le fichier n''a pas ‚t‚ trouv‚ :'                                                                                   
      HK(40,4)='Arkivet v†r ikke funnet :'                                                                                          
                                                                                                                                    
      HK(41,1)='Output page width in characters (e.g. 80..132) ?'                                                                   
      HK(41,2)='Ancho de la p gina de salida en c racteres'             &                                                           
     *//' (e.g. 80..132) ?'                                                                                                         
      HK(41,3)='Largeur de la page du fichier de resultats '            &                                                           
     * //' (numero de lettres, e.g. 80..132)'                                                                                       
      HK(41,4)='Utside utformingsbredde (tegn e.g. 80..132) ?'                                                                      
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
                                                                                                                                    
