install.packages('ggplot2')
   plot(1,3)
install.packages('gam')
data()
data(ple4)
ls()
b=(1:5)
length(b)
as.FLQuant(data.frame(age = 1:10,data 0li.2))
flq<- window(landings.n(ple4),start=1995,end=2001)
dimnames(flq)
getClassMethods("FLQuant","package:LFCore")
getClassMethods("FLQuant", "package:FLCore")
showMethods(classes="FLQuant")
dimnames(flq)
showClass("FLStock")
summary(ple4)
summary(nsher)
data(nsher)