# catch.obs {{{
setGeneric('catch.obs', function(object, ...)
		standardGeneric('catch.obs'))
setGeneric('biomass.obs', function(object, ...)
		standardGeneric('biomass.obs'))
setGeneric('yield.obs', function(object, ...)
		standardGeneric('yield.obs'))
setGeneric('computeFbar', function(object, ...)
		standardGeneric('computeFbar'))
setGeneric('rec', function(object, ...)
		standardGeneric('rec'))
setGeneric('rec.hat', function(object, ...)
   standardGeneric('rec.hat'))
setGeneric('spr', function(object, ...)
		standardGeneric('spr'))
setGeneric('ypr', function(object, ...)
		standardGeneric('ypr'))
setGeneric('computeRefpts', function(object, ...)
		standardGeneric('computeRefpts'))
setGeneric('brp', function(object, ...)
		standardGeneric('brp'))
setGeneric('hcrYield', function(object, fbar, ...)
		standardGeneric('hcrYield'))
setGeneric('catch.hat', function(object, ...)
		standardGeneric('catch.hat'))
setGeneric('yield', function(object, ...)
		standardGeneric('yield'))
setGeneric('yield.hat', function(object, ...)
		standardGeneric('yield.hat'))
setGeneric('discards.hat', function(object, ...)
		standardGeneric('discards.hat'))
setGeneric('landings.hat', function(object, ...)
		standardGeneric('landings.hat'))
setGeneric('stock.hat', function(object, ...)
		standardGeneric('stock.hat'))
setGeneric('ssb.hat', function(object, ...)
		standardGeneric('ssb.hat'))
setGeneric('cost', function(object, ...)
		standardGeneric('cost'))
setGeneric('profit', function(object, ...)
		standardGeneric('profit'))
setGeneric('profit.hat', function(object, ...)
		standardGeneric('profit.hat'))
setGeneric('bycatch.hat', function(object, ...)
		standardGeneric('bycatch.hat'))
setGeneric('bycatch', function(object, ...)
		standardGeneric('bycatch'))
setGeneric('bycatch.n', function(object, ...)
		standardGeneric('bycatch.n'))
if (!isGeneric("refpts"))
	setGeneric("refpts", function(object, ...)
		standardGeneric("refpts"))
if (!isGeneric("refpts<-"))
	setGeneric("refpts<-", function(object, ..., value)
		standardGeneric("refpts<-"))
setGeneric("msy", function(object)
		standardGeneric("msy"))
