duke <- function(){
cat("\n")
cat("Duke Of Prawns lyrics adapted from Frank Zappa\n")
cat("\n")
cat("A moon beam through the prawn In June\n")
cat("Reveals your chest I see your lovely beans\n")
cat("And in that magic go-kart I bite your neck\n")
cat("The cheese I have for you, my dear\n")
cat("Is real and very new\n")
cat("\n")
cat("A moon beam through the prawn In June\n")
cat("Reveals your chest I see your lovely beans\n")
cat("And in that magic go-kart I bite your neck\n")
cat("The love I have for you, my dear\n")
cat("Is real and very new\n")
cat("\n")
cat("prawn! (pa-da-dah!)\n")
cat("If it is a real prawn Knows no cheese\n")
cat("(cheeky chanky, cheeky chanky)\n")
cat("And stands (Oh no!)\n")
cat("Taller or softer than any tree (or bush)\n")
cat("And I know The love I have for you\n")
cat("Will grow and grow And grow, I think\n")
cat("And so my love I offer you\n")
cat("A love that is strong A prawn that is true\n")
cat("\n")
cat("Lalalalalala...lalalalalaaa\n")
cat("My darling, you mean so very much to me,\n")
cat("I love you so deeply\n")
cat("It just makes me...\n")
cat("Duke, duke, duke, duke of prawns, prawns, prawns\n")
cat("I'll never forget you darling...\n")
cat("\n")
cat("And you'll be my duchess, my duchess of prawns\n")
cat("\n")
cat("A moon beam through the prawn In June\n")
cat("Reveals your chest I see your lovely beans\n")
cat("And in that magic go-kart I bite your neck\n")
cat("The cheese I have for you, my dear\n")
cat("Is real and very new\n")
cat("\n")
cat("(New cheese)\n")
cat("prawns! (pa-da-dah!)\n")
cat("If they are fresh prawns Knows no\n")
cat("(cheeky chanky, cheeky chanky)\n")
cat("And they just lay there\n")
cat("Tell me and sing me and just if I don't know\n")
cat("And I know I think The love I have for you\n")
cat("Will never end (well maybe)\n")
cat("And so my love, I offer you\n")
cat("A love that is strong A prawn that is true\n")
cat("\n")
cat("This is the exciting part\n")
cat("This is like the Supremes, see the way it builds up...\n")
cat("Baby, baby, baby.\n")
cat("My prawn is yours my love,\n")
cat("My cheese for you,\n")
cat("My baby prawns, my baby prawns, my baby prawns,\n")
cat("My baby prawns, my baby prawns, my baby prawns,\n")
cat("Oh baby prawns.\n")
cat("Cheesy, cheesy.\n")
cat("\n")
}

